version: '3'

networks:
 webnet:
  driver: bridge

services:
 jaeger:
  image: jaegertracing/all-in-one:1.8
  environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  ports: 
   - "5775:5775/udp"
   - "6831:6831/udp"
   - "6832:6832/udp"
   - "5778:5778"
   - "16686:16686"
   - "14268:14268"
   - "9411:9411"
  networks: 
    - webnet
  hostname: "jaeger"

 prom:
  build: ./prometheus
  command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
  ports:
   - "9090:9090"
  depends_on:
   - exporter
  networks: 
   - webnet

 exporter:
   image: prom/node-exporter:latest
   ports:
     - "9100:9100"
   networks: 
    - webnet

 grafana:
   image: grafana/grafana
   ports:
    - "4000:4000"
   depends_on:
    - prom
   networks: 
    - webnet

